### PR TITLE
Added support for function validation

### PR DESCRIPTION
**Pull request by carrerasrodrigo**
Hello @1000hz,

I closed a previous pull request because I added some lines by mistake. I create a new pull request without it. 
Added a new validation that allows to call function in order to validate. data-fnvalidation=‘function_name’.

I hope it can be merged! Gracias!!

### CODE REVIEW

**Comment by ty-** [comment]
@1000hz, any chance this can be merged?

**Comment by ty-** [comment]
@1000hz ping

**Comment by 1000hz** [comment]
Sorry, I haven't had much time to really focus on this. This pull request doesn't have the ideal API in my opinion, which is why I haven't merged it yet.

What I have in mind is something like

```js
$('#myForm').validator({
  custom: {
    foo: function () {
      return $(this).val() === $(this).data('foo')
    },
    bar: function () {
      return $(this).val() !== $(this).data('bar')
    }
  },
  errors: {
    foo: 'Not foo',
    bar: 'Value is bar'
  }
})
```

```html
<input type="text" data-foo="foo value" data-bar="bar value"/>
```

As soon as I have time for the next major release, I'm gonna implement this.

**Comment by ty-** [comment]
Thank you for the update.

**Comment by 1000hz** [comment]
I just released v0.8.0 with support for custom validators

**Comment by fishermand46** [comment]
:+1:

**Comment by ty-** [comment]
+1

**Pull request closed without merging**
