### PR TITLE
Improve validation feedback using has-success and support for form-control-feedback

### PR DESCRIPTION
**Pull request by r0ro**

### CODE REVIEW

**Comment by 1000hz** [comment]
Looks good. Thanks!

**Comment by darylknight** [comment]
As far as I can see, nothing happens when the field validates. Errors appear correctly but the 'has-success' class never appears. Am I missing something?

**Comment by r0ro** [comment]
Do you use something like that :

```html
<div class="form-group has-feedback">
      <input type="email" class="form-control"
             name="email" placeholder="Email" required />
      <span class="glyphicon form-control-feedback"></span>
      <div class="help-block with-errors"></div>
</div>
```

**Comment by darylknight** [comment]
Ah, I was using the help block but expected the plugin to add the necessary success classes. Fixed, thanks.

**Comment by cyberbit** [comment]
Looks like the success handling doesn't trigger properly if the feedback icon isn't included.
image
Name input has glyphicon element, Twitter input does not. Fiddle: http://jsfiddle.net/cyberbit/7zwsjj49/

**Pull request merged**
