### PR TITLE
Added validator('reset') to index.html

### PR DESCRIPTION
**Pull request by dstran**
This is missing from documentation:

`$(...).validator('reset')` 

I found this feature from searching PRs. This will be helpful for people using this library.

### CODE REVIEW

**Comment by 1000hz** [comment]
It's not meant to be part of the public API. It gets called automatically when the form is reset.

**Comment by dstran** [comment]
Hmm, the current v0.11.5 exposes this now. I'm using this library on my
angular project and I needed this to reset the validation state when
switching data entry objects.

For example, user1 is validated to have invalid field. Then, I switched to
user2. Without reset, user2 will show invalid fields.

Do you recommend another way to do this?

Thanks,
David

**Comment by 1000hz** [comment]
It's on the prototype, so it's technically accessible by calling `.validator('reset')` but that doesn't mean it's necessarily part of the recommended public interface.

If you call `$('#myUserForm').trigger('reset')` or `myFormElement.reset()`. Let me know if resetting your form isn't an option and I'll consider elevating this to the public API. I'm not against it, but if it can be avoided I'd rather not increase the breadth of the API.

**Comment by dstran** [comment]
Yes, `$('#myUserForm').trigger('reset')` works. As a side note, I needed to call `.validator('update')` since not all elements are on the DOM due to how angular loads. So, it's natural for me to call `reset` and didn't think of using jquery's `trigger`. 

Like I said, `trigger` works so I can use that. I'm wondering your reasoning for making an API public vs not.

Also, the way I'm mixing your validation versus my server validation, I'm wondering if there's a way to force the check mark to be a cross mark?  After submission (like email is already in use.), I can show the error but it's still checked. Technically, it's checked because the email is valid. What's the correct way to do this. Thanks again for your help!

**Comment by dstran** [comment]
I figure out how to force a cross mark using angular way. Thanks again.

**Comment by 1000hz** [comment]
> I'm wondering your reasoning for making an API public vs not.

My goal is to make the plugin as simple as possible to use. The more options and methods the plugin has, the more daunting of a task it is for new users to understand it. I want as much of the plugin's ideal behavior to happen without the user having to think about it or write extra code for it.

In the case of `Validator.prototype.reset`, it was added because people were resetting their forms and finding that the validator state was still persisting. It made sense to just clear the validator state automatically as a result of the form being reset.

**Pull request closed without merging**
