### PR TITLE
Support file type validation

### PR DESCRIPTION
**Pull request by debbbbie**
The true reason is that I need to validate the file size before submitting.

How do you think about this?

### CODE REVIEW

**Comment by 1000hz** [comment]
This sort of thing would be better handled with a custom validator. Here's an example to add filesize validation:

http://jsbin.com/wavodepuni/edit?html,js,output

**Comment by debbbbie** [comment]
@1000hz Good Job! Could you please add it to wiki page or readme? Thus, someone who has the same demand would be surprised !

**Comment by surgiie** [comment]
Is there a way to do file mime type validation?

**Comment by surgiie** [comment]
Is there file mime type validation available?

**Comment by 1000hz** [comment]
@surgiie Check out the `accept` attribute on file input fields
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input

It's standard browser behavior (not a part of this plugin), but it should prevent a user from choosing files of invalid types in most browsers. If you need something more robust, you can write a custom validator similar to the filesize example linked above.

**Comment by surgiie** [comment]
@1000hz  Thanks. This will work. I plan on doing server side validation on top of using this plugin so i wasnt sure if there was mime type validation as well, but this will work!! Thanks again.

**Pull request closed without merging**
