### PR TITLE
updates to support callable validator methods with return value

### PR DESCRIPTION
**Pull request by leobm**
+ update library dependencies
+ update qunit tests

### CODE REVIEW

**Comment by 1000hz** [comment]
Methods with return values are not intended to be part of the public API.

**Comment by leobm** [comment]
I know my solution is not really clean. I needed a way to ask the validator for errors/complete status, 
without duplicating the code.
In the old code I could call the hasErrors method too, but without a return value. All Validator methods are currently public in general. Do you have a better idea?

**Comment by 1000hz** [comment]
You can get a reference to the Validator instance via $('#myForm').data('bs.validator') and call the methods on that.

**Comment by leobm** [comment]
ok, thanks. 

But I tried another thing
https://github.com/leobm/bootstrap-validator/commit/98bde5411d8c8d717605eb2d7aad58dfa3dd8fb7

**Comment by leobm** [comment]
but I think to get the validator by the element data is ok for me.

**Pull request closed without merging**
