### PR TITLE
Fix multiple bugs with the disabled option

### PR DESCRIPTION
**Pull request by marten-seemann**
I contributed the *disabled* option some time ago (1000hz/bootstrap-validator/pull/46).

I discovered that now there are two problems with this option:
1. focussing the erroneous input element does not work.
2. the form is submitted, even though it contains validation errors.

Both errors stem from the same source, since in both functions (`focusError` and `onSubmit`) it is determined if the form contains errors by calling `this.$btn.hasClass('disabled')`, where `$btn` is the submit button. However, when the *disabled* option is set, the submit button is never disabled.

This pull request fixes these two bugs by using other ways to check if the form contains validation errors.

### CODE REVIEW

**Comment by marten-seemann** [comment]
@1000hz Any comments on that?

**Comment by 1000hz** [comment]
Looks good. Just make sure your `if ()` statements have a space before the opening parenthesis and I'll merge. Thanks!

**Comment by marten-seemann** [comment]
Done.

**Comment by 1000hz** [comment]
Thanks for this. I'm surprised nobody reported the form submit issue sooner. 😬

**Comment by marten-seemann** [comment]
No problem. Thanks for merging so quickly.
When do you plan to do the next release? That would make it easier for me to deploy the fix.

**Comment by 1000hz** [comment]
I'll try to do it some time tomorrow if I don't forget. It's late right now and I'm tired. If I haven't released it in a couple days, feel free to ping me in this thread.

**Pull request merged**
